---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-dev
resources:
  - ../../base
patches:
  - path: patches/server-replicas.yaml
  - path: patches/web-replicas.yaml
  - path: patches/ingress-host.yaml
  - path: patches/config-overrides.yaml
