---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: longread-blog

patchesStrategicMerge:
  - replicas-patch.yaml
  - resources-patch.yaml

configMapGenerator:
  - name: longread-config
    behavior: merge
    literals:
      - LOG_LEVEL=debug
      - NODE_ENV=development

images:
  - name: longread-backend
    newTag: latest
  - name: longread-frontend
    newTag: latest

commonLabels:
  environment: development
